[package]
name = "seemoo"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [
    "Roland Schätzle <@roland-KA>",
    "Stefan Siber <@stefan-ctrl>",
    "Tobias Müller <otsmr>",
]
license = "MIT"
description = "Computer Science Thesis for the SEEMOO Lab of the TU Darmstadt"
repository = "https://github.com/otsmr/seemoo-typst-template"
keywords = ["seemoo", "Darmstadt", "thesis"]
categories = ["paper", "thesis", "report"]
exclude = ["template/main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
